### ISSUE TITLE
nightly namedtype doesn't install

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#371]
```
2020-07-20 21:14:57,112 lib.installation ERROR    libraries/c++/nightly/namedtype/trunk installed OK, but doesn't appear as installed after
```

**Comment by partouf** [comment]
```
namedtype:
        type: github
        method: nightlyclone
        repo: joboccara/NamedType
        path_name: libs/NamedType
        check_file: named_type.hpp
        build_type: none
        targets:
          - trunk
```
